### ISSUE TITLE
smtp_login ValueError with ssl=1

### ISSUE THREAD

**Issue by Anquetos** [lanjelot/patator#129]
Hello,

I've searched for a few days but I didn't managed to get my command to work.
I'm trying to do the following command:
`patator smtp_login ssl=1 port=465 host=smtp.gmail.com user=xxxxx@gmail.com password=xxxxx`
but I get that answer:
````
21:32:01 patator    FAIL - xxx   91     1.207 |
|     1 | <class 'ValueError'> server_hostname cannot be an empty string or start with a leading dot.
21:32:01 patator    INFO - Hits/Done/Skip/Fail/Size: 0/1/0/1/1, Avg: 0 r/s, Time: 0h 0m 2s
````

Do you have any clue for me?

Thank you

**Comment by lanjelot** [comment]
No idea mate, your command line works fine with either Python-3.6.9 or Python-2.7.17

```
$ patator.py smtp_login ssl=1 port=465 host=smtp.gmail.com user=xxxxx@gmail.com password=xxxxx
03:03:22 patator    INFO - Starting Patator v0.7 (https://github.com/lanjelot/patator) at 2020-03-21 03:03 UTC
03:03:22 patator    INFO -                                                                                         
03:03:22 patator    INFO - code  size    time | candidate                          |   num | mesg       
03:03:22 patator    INFO - -----------------------------------------------------------------------------                                                                                                                                       
                                                                                                                                                                                                                                               
03:03:26 patator    INFO - 535   140    1.224 |                                    |     1 | 5.7.8 Username and Password not accepted. Learn more at                                                                                           
5.7.8  https://support.google.com/mail/?p=BadCredentials e24sm6729150pfi.200 - gsmtp
03:03:26 patator    INFO - Hits/Done/Skip/Fail/Size: 1/1/0/0/1, Avg: 0 r/s, Time: 0h 0m 3s
```

**Comment by icekill** [comment]
Hi,

Same behaviour for me: 
patator smtp_login host=smtp.gmail.com user=xxxxx@xxxxx password=FILE0 0=/usr/share/passwd_list.lst ssl=1 persistent=1 timeout=1 starttls=1 port=465

patator    FAIL - xxx   91     1.212 | summer                             |    30 | <class 'ValueError'> server_hostname cannot be an empty string or start with a leading dot.

 /usr/bin/python --version
Python 2.7.18

/usr/bin/python3 --version
Python 3.8.5

Many thanks for Patator!

**Comment by lanjelot** [comment]
What version is this? Can you please paste the first line of the output which contains the version infos?

**Comment by icekill** [comment]
01:54:27 patator    INFO - Starting Patator 0.8 (https://github.com/lanjelot/patator) with python-3.8.5 at 2020-08-01 01:54 EDT

**Comment by lanjelot** [comment]
Can you try with the latest 0.9 version please?

**Comment by icekill** [comment]
I have uninstalled patator from Kali and reinstalled it:

root@kali:/tmp# apt-get install patator
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  python3-ajpy python3-pysmi python3-pysnmp4
The following NEW packages will be installed:
  patator python3-ajpy python3-pysmi python3-pysnmp4
0 upgraded, 4 newly installed, 0 to remove and 3 not upgraded.
Need to get 0 B/278 kB of archives.
After this operation, 1,898 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Selecting previously unselected package python3-ajpy.
(Reading database ... 337447 files and directories currently installed.)
Preparing to unpack .../python3-ajpy_0.0.4-2_all.deb ...
Unpacking python3-ajpy (0.0.4-2) ...
Selecting previously unselected package python3-pysmi.
Preparing to unpack .../python3-pysmi_0.3.2-2_all.deb ...
Unpacking python3-pysmi (0.3.2-2) ...
Selecting previously unselected package python3-pysnmp4.
Preparing to unpack .../python3-pysnmp4_4.4.6+repack1-2_all.deb ...
Unpacking python3-pysnmp4 (4.4.6+repack1-2) ...
Selecting previously unselected package patator.
Preparing to unpack .../archives/patator_0.8-1_all.deb ...
Unpacking patator (0.8-1) ...
Setting up python3-pysmi (0.3.2-2) ...
Setting up python3-ajpy (0.0.4-2) ...
Setting up python3-pysnmp4 (4.4.6+repack1-2) ...
Setting up patator (0.8-1) ...
Processing triggers for kali-menu (2020.3.2) ...
Processing triggers for man-db (2.9.3-2) ...

**Patator 0.8.1 is installed, not the latest version. Thus I have tried pip install patator :**

root@kali:/tmp# pip install patator
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting patator
  Using cached patator-0.9.tar.gz (58 kB)
Collecting IPy
  Using cached IPy-1.00.tar.gz (35 kB)
Collecting ajpy
  Using cached ajpy-0.0.5.tar.gz (6.2 kB)
Collecting cx_Oracle
  Using cached cx_Oracle-8.0.0.tar.gz (325 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-FDN4x7/cx-oracle/setup.py'"'"'; __file__='"'"'/tmp/pip-install-FDN4x7/cx-oracle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8LOdfI
         cwd: /tmp/pip-install-FDN4x7/cx-oracle/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-FDN4x7/cx-oracle/setup.py", line 17, in <module>
        raise Exception("Python 3.5 or higher is required.")
    Exception: Python 3.5 or higher is required.                                                                                                                                                 
    ----------------------------------------                                                                                                                                                     
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Assuming that it's a question of python version, I have tried:**

pip3 install patator
Collecting patator
  Using cached patator-0.9-py3-none-any.whl (53 kB)
Requirement already satisfied: pyopenssl in /usr/lib/python3/dist-packages (from patator) (19.1.0)
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (from patator) (2.7.1)
Requirement already satisfied: ajpy in /usr/local/lib/python3.8/dist-packages (from patator) (0.0.5)
Requirement already satisfied: pyasn1 in /usr/lib/python3/dist-packages (from patator) (0.4.8)
Requirement already satisfied: pysnmp in /usr/local/lib/python3.8/dist-packages (from patator) (4.4.12)
Requirement already satisfied: impacket in /usr/local/lib/python3.8/dist-packages (from patator) (0.9.22.dev1+20200728.230151.48a3124c)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from patator) (1.16.0)
Requirement already satisfied: cx-Oracle in /usr/local/lib/python3.8/dist-packages (from patator) (8.0.0)
Collecting pysqlcipher3
  Using cached pysqlcipher3-1.0.3.tar.gz (100 kB)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.8/dist-packages (from patator) (2.8.5)
Requirement already satisfied: mysqlclient in /usr/lib/python3/dist-packages (from patator) (1.4.4)
Requirement already satisfied: pycurl in /usr/lib/python3/dist-packages (from patator) (7.43.0.2)
Requirement already satisfied: pycrypto in /usr/lib/python3/dist-packages (from patator) (2.6.1)
Requirement already satisfied: IPy in /usr/lib/python3/dist-packages (from patator) (1.0)
Requirement already satisfied: pysmi in /usr/local/lib/python3.8/dist-packages (from pysnmp->patator) (0.3.4)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from pysnmp->patator) (3.9.7)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket->patator) (0.9.3)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket->patator) (2.7)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket->patator) (1.1.2)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket->patator) (1.15.0)
Requirement already satisfied: ply in /usr/lib/python3/dist-packages (from pysmi->pysnmp->patator) (3.11)
Building wheels for collected packages: pysqlcipher3
  Building wheel for pysqlcipher3 (setup.py) ... done
  WARNING: Legacy build of wheel for 'pysqlcipher3' created no files.
  Command arguments: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g9rdkzca/pysqlcipher3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g9rdkzca/pysqlcipher3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-sczssj93                                                                                                                                                                 
  Command output: [use --verbose to show]                                                                                                                                                        
  Running setup.py clean for pysqlcipher3
Failed to build pysqlcipher3
Installing collected packages: pysqlcipher3, patator
    Running setup.py install for pysqlcipher3 ... done
Successfully installed patator-0.9 pysqlcipher3

**Comment by lanjelot** [comment]
Please use the provided Dockerfile if you're not able to install Patator on your host system.
