### ISSUE TITLE
Suggestion: add different options to bruteforce

### ISSUE THREAD

**Issue by CowardMonkey** [lanjelot/patator#171]
**Add the possibility to choose from different bruteforce methods like:**
**-b1** ((user1 : password1) (user2 : password2) (user3 : password3)....)
**-b2** ((user1: password1) (user1 : password2) (user2 : password1) (user2 : password2))

**Comment by lanjelot** [comment]
nope, for 2 reasons:
- by design the controller is module-purpose agnostic i.e has no idea what the module is meant to attack/bruteforce/test, could be testing creds, could be testing exploits...
- it is already possible to iterate over given wordlists in various ways and accomplish what you are suggesting https://github.com/lanjelot/patator/blob/master/patator.py#L201-L233
