### ISSUE TITLE
A freerdp version check should be included

### ISSUE THREAD

**Issue by nikosdano** [lanjelot/patator#35]
In a system where the version of FreeRDP 1.0.2 or previous, patator will return the following error:  

"protocol security negotiation failure". This is an error coming from FreeRDP because of the invalid options used. 

Of course this is not Patator's fault. But by adding an extra check for the version of freerdp many people will know what they have to do to fix it the error.

Older FreeRDP version use this structure for accessing desktops:
Username with -u, password with -p and so on and so forth. 
While, patator supposing the FreeRDP is the latest, it uses the /:v , /:u and /:p command structure.

An idea might be to provide support for even the old structure. Otherwise, an version check of the freerdp might be useful for the feature users that will encounter this error.

**Comment by lanjelot** [comment]
Thanks for reporting this but unfortunately, I don't want to waste my time on adding support for old FreeRDP versions. Plus I'd really like to use impacket's RDP implementation instead of dumbly executing xfreerdp. FWIW patator actually expects version 1.2.0 or above: https://github.com/lanjelot/patator/blob/master/patator.py#L138
