### ISSUE TITLE
Multiple header not supported

### ISSUE THREAD

**Issue by alisonliu** [lanjelot/patator#74]
Multiple headers cannot be parsed correctly. 
For example, I tried to use 
`patator http_fuzz header='Referer: xyz, Cookie: xyz' url=localhost:8080`
Only one header will be parsed. It would be 'Referer' header in this case, therefore omitting 'Cookie' header.

**Comment by lanjelot** [comment]
https://github.com/lanjelot/patator/blob/master/patator.py#L399

**Comment by newlog** [comment]
hey @lanjelot , awesome work. I discovered your tool not long ago and it's wonderful.

I just want to leave this comment in case it's helpful for anyone else (as it took me one hour to find the answer). If you want patator to honor more than one header, in the "header" parameter use the  "@<filename>" syntax instead of "FILE<n>".

I thought that @filename and FILE<n> was the same but one let you specify the path of the file directly in the parameter instead of having to add one more argument to the commandline. It is not the case. What @<filename> does is NOT to iterate over the entries in the file you specify.

A command line example:
`patator http_fuzz url=https://127.0.0.1:8082 method=POST body='{"identification":"admin","password":FILE0}' auto_urlencode=0 -x ignore:code!=403 --allow-ignore-failures header=@header.txt 0=/usr/share/seclists/Passwords/Leaked-Databases/rockyou-75.txt`

Where header.txt contains:

`Content-Type: application/json; charset=utf-8
X-CSRF-Token: <token1>
Cookie: session=<token2>`

As a bonus, with this example you can see how to bruteforce JSON requests.

I couldn't find this in the documentation or anywhere else in the internet. Being honest, I just read the http_fuzz docs and skimmed other parts. It would be interesting to add this somewhere else in the docs.

**Comment by lanjelot** [comment]
thanks for the kind words. I agree it is not a well-documented feature, it's demo'ed once in the examples:
https://github.com/lanjelot/patator/blob/master/patator.py#L419
