### ISSUE TITLE
BUG? incorrect syntax? New feature needed?

### ISSUE THREAD

**Issue by BerKut81** [lanjelot/patator#93]
Hello Patator God, I'm a super rookie patator user.

I think that I detected a bug or a new situation not viewed before. Please, let me explain you:

I was checking the GETs to the login page (there is no POSTs). Everything looks very normal, is a basic http authentication (user:password, all encoded in base64). But, I found there is no matter what password I'm using, Patator always understand that the password is correct using http_fuzz.

I was taking a look at the response packets and the server always answer with a 200. The only way I can recognize a successful or unsuccessful login attempt was using reading the HTML code at response.

Is there any way to do a basic http authentication not using response code in order to validate if the authentication is OK or not? I can't find anything clear at Patator documentation or the http_fuzz code.

Using this parameters, Patator find every password as OK:
patator http_fuzz method=GET url=http://192.168.10.1/ auth_type='basic' user_pass=admin:SuperPassword -x ignore:fgrep='incorrect,'

I forget to add this link with exactly the same situation (maybe there is a better explanation):
. https://stackoverflow.com/questions/32671292/determine-whether-a-basic-authentication-login-was-successful

Thanks in advance.-

**Comment by gildasio** [comment]
@BerKut81 I don't know if it was implemented after or before your question but there is a `!=` operation you could use for that.

~~~
patator http_fuzz method=GET url=http://192.168.10.1/ auth_type='basic' user_pass=admin:SuperPassword -x ignore:fgrep!='incorrect,'
~~~

This example above should work.

You or @lanjelot, I think you guys can close this issue.

**Comment by lanjelot** [comment]
Hey there, thanks for your messages.

So actually it's important to understand that Patator has no idea whether a login attempt succeeded or not. Patator only reports every response back to the user, and it's up to the user to decide what responses are associated to incorrect or correct creds.

So in your case since you always get 200, i would be more specific with the ignore action and pass something like -x ignore:code=200,size=400-500,fgrep=incorrect for example.
